### ISSUE TITLE
Angular of the Universe

### ISSUE THREAD

**Issue by bennofs** [ALLESCTFTeam/ctf#13]
You know, everything has the angular.
A bread, you, me and even the universe.
Do you know the answer?

http://universe.chal.ctf.westerns.tokyo

universal-angular.zip

@DeeJayBro @OlfillasOdikno EPG layton

**Comment by OlfillasOdikno** [comment]
I lost nearly all data for this challenge and won't be able to solve it again/write the writeup this weekend. Someone else has to do it, sorry..
