### ISSUE TITLE
Does Linux Dream of Windows?

### ISSUE THREAD

**Issue by bennofs** [ALLESCTFTeam/ctf#14]
Tux is dreaming of Windows.
http://dream.chal.ctf.westerns.tokyo/
dream.7z

Hint: apache2.tar.gz
Hint2 (2020-09-19 20:00:00 UTC): Did you try "Back To Top" from upload.aspx? What's happening?
Hint3 (2020-09-19 20:00:00 UTC): etc.tar.gz

@OlfillasOdikno @DeeJayBro loknop

**Comment by OlfillasOdikno** [comment]
I lost nearly all data for this challenge and won't be able to solve it again/write the writeup this weekend. Someone else has to do it, sorry..
